#!/bin/sh
echo "Sending AT+QFASTBOOT..."
sudo sh -c 'echo -ne "AT+QFASTBOOT\r" > /dev/ttyUSB2'
echo "Sending OEM STAY in case the custom bootloader is installed"
fastboot oem stay
echo "Waiting to settle..."
sleep 2
echo "Start flashing!"
fastboot flash aboot appsboot.mbn || exit "Failed to flash the bootloader"
fastboot flash:raw boot mdm9607-boot.img || exit "Failed to flash main kernel"
fastboot flash:raw recovery mdm9607-boot.img || exit "Failed to flash recovery kernel"
fastboot flash system mdm9607-sysfs.ubi || exit "Failed to flash the system partition"
fastboot flash recoveryfs mdm9607-recovery.ubi || exit "Failed to flash the recovery partition"
fastboot reboot
echo "Done!"